/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//...
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import model.Frm_Chasier;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Azka
 */
public class Cashier extends javax.swing.JFrame {
    Connection con;
    Statement stmt;
    PreparedStatement stat;
    ResultSet rs;
ResultSet rs1;
    DefaultTableModel mdl3;
    DefaultTableModel mdl4;
//...

//....
    private void Number (java.awt.event.KeyEvent evt)
    {
       char c = evt.getKeyChar();
           if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))
           {
                evt.consume();
           }
    }

    /**
     * Creates new form a
     */
    public Cashier() {
        initComponents();
        setTitle("Transaction");
//tampil tablepro//
        String[] judul={"ID Product","Title", "Artist", "IDGenre", "Price", "Stock"};
        mdl3 = new DefaultTableModel(judul,0);
        tballpro.setModel(mdl3);
        tampilkan1();

        tballpro.setPreferredScrollableViewportSize(new Dimension(300,300));
        tballpro.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

//tampil tableDetTrans//
//        String[] dettrans={"IDDetTrans", "IDTrans", "ID Product","Title", "Price", "Qty","SubTotal" };
//        mdl4 = new DefaultTableModel(dettrans,0);
//        tbDTrans.setModel(mdl4);
//        //tampilkan2();
//
//        tbDTrans.setPreferredScrollableViewportSize(new Dimension(300,300));
//        tbDTrans.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
//Connection Database
        String connectionUrl = "jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930";
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }catch(Exception e){
            System.out.println(e);
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtpayment = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tstock1 = new javax.swing.JTextField();
        countchange = new javax.swing.JButton();
        change1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        qty1 = new javax.swing.JTextField();
        addpro = new javax.swing.JButton();
        count1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        idemp1 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbIDHeader = new javax.swing.JLabel();
        newTrans = new javax.swing.JButton();
        stitle = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        idtotrans = new javax.swing.JTextField();
        idDT = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDTrans = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tballpro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        tidpro1 = new javax.swing.JTextField();
        ttitle1 = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        tprice1 = new javax.swing.JTextField();
        subtot = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnlogout1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel9.setText("Total");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel10.setText("Payment");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        txtpayment.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        txtpayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpaymentActionPerformed(evt);
            }
        });
        txtpayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpaymentKeyTyped(evt);
            }
        });
        jPanel2.add(txtpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 120, -1));

        jLabel22.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel22.setText("Stock");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));
        jPanel2.add(tstock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 120, -1));

        countchange.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        countchange.setText("Change");
        countchange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countchangeMouseClicked(evt);
            }
        });
        countchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countchangeActionPerformed(evt);
            }
        });
        jPanel2.add(countchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 100, -1));

        change1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        change1.setText("change*");
        jPanel2.add(change1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel3.setText("Date");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel5.setText("ID Emp");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        date1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        date1.setText("Date");
        jPanel2.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, -1));

        jLabel17.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel17.setText("SubTotal");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        jLabel18.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel18.setText("Quantity");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        qty1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        qty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qty1ActionPerformed(evt);
            }
        });
        qty1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qty1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qty1KeyTyped(evt);
            }
        });
        jPanel2.add(qty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 120, 30));

        addpro.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        addpro.setText("Add");
        addpro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addproMouseClicked(evt);
            }
        });
        addpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addproActionPerformed(evt);
            }
        });
        jPanel2.add(addpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 100, -1));

        count1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        count1.setText("Count");
        count1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                count1MouseClicked(evt);
            }
        });
        count1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count1ActionPerformed(evt);
            }
        });
        jPanel2.add(count1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 100, -1));

        jLabel19.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel19.setText("ID Product");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));

        jLabel20.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel20.setText("Search title");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 100, 30));

        jLabel21.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel21.setText("Price");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        idemp1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        idemp1.setText("ID Emp");
        jPanel2.add(idemp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jLabel23.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel23.setText("Title");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, -1, -1));

        lbIDHeader.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        lbIDHeader.setText("idTH");
        jPanel2.add(lbIDHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        newTrans.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        newTrans.setText("New Trans");
        newTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newTransMouseClicked(evt);
            }
        });
        newTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTransActionPerformed(evt);
            }
        });
        jPanel2.add(newTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        stitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stitleActionPerformed(evt);
            }
        });
        stitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stitleKeyTyped(evt);
            }
        });
        jPanel2.add(stitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 320, 30));

        jLabel16.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel16.setText("Change");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, -1, -1));

        idtotrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtotransActionPerformed(evt);
            }
        });
        jPanel2.add(idtotrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 30, -1));

        idDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDTActionPerformed(evt);
            }
        });
        jPanel2.add(idDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 30, -1));

        tbDTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDTrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDTransMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbDTrans);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 400, 130));

        tballpro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tballpro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tballproMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tballpro);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 440, 220));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        jLabel1.setText("IDTransHeader");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        cancel.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 100, -1));

        tidpro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidpro1ActionPerformed(evt);
            }
        });
        jPanel2.add(tidpro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 90, -1));
        jPanel2.add(ttitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 240, -1));

        total.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        total.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalKeyTyped(evt);
            }
        });
        jPanel2.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 120, 30));
        jPanel2.add(tprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 120, -1));

        subtot.setFont(new java.awt.Font("Lucida Calligraphy", 0, 14)); // NOI18N
        subtot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotActionPerformed(evt);
            }
        });
        subtot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                subtotKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                subtotKeyTyped(evt);
            }
        });
        jPanel2.add(subtot, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 120, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 910, 480));

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 190, 148));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/cashiersss.png"))); // NOI18N
        jLabel4.setText("Cashier");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 290, 90));

        btnlogout1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlogout1.setText("Logout");
        btnlogout1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogout1MouseClicked(evt);
            }
        });
        btnlogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogout1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg2.jpg"))); // NOI18N
        jLabel2.setText("BGfilm");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -290, 910, 990));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   public void autodetail()
    {
        try
        {
            String sql = "select top 1 IDDetTrans FROM DetailTransac order by IDDetTrans desc";
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery(sql);
            
            if(rs.next())
            {
                String ID = rs.getString("IDDetTrans");
                String potong = ID.substring(1);
                int nextid = Integer.parseInt(potong) + 1;
                
                if (nextid<10)
                {
                    ID = "4000" + nextid;
                }
                else if (nextid < 100)
                {
                    ID = "400" + nextid;
                }
                else if (nextid < 1000)
                {
                    ID = "40" + nextid;
                }
                else if (nextid < 10000)
                {
                    ID = "4" + nextid;
                }
                idDT.setText(ID);
                
            }
            else
            {
                idDT.setText("40001");
            }
         }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }

   public void autoidT()
    {
        try
        {
            String sql = "select top 1 IDTotTrans FROM TotalTrans order by IDTotTrans desc";
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery(sql);
            
            if(rs.next())
            {
                String ID = rs.getString("IDTotTrans");
                String potong = ID.substring(1);
                int nextid = Integer.parseInt(potong) + 1;
                
                if (nextid<10)
                {
                    ID = "9000" + nextid;
                }
                else if (nextid < 100)
                {
                    ID = "900" + nextid;
                }
                else if (nextid < 1000)
                {
                    ID = "90" + nextid;
                }
                else if (nextid < 10000)
                {
                    ID = "9" + nextid;
                }
                idtotrans.setText(ID);
                
            }
            else
            {
                idtotrans.setText("90001");
            }
         }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void btnlogout1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogout1MouseClicked
        // TODO add your handling code here:
        MainMenu1 mu = new MainMenu1();
        mu.show();
        this.hide();
    }//GEN-LAST:event_btnlogout1MouseClicked

    private void btnlogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogout1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlogout1ActionPerformed

    private void txtpaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpaymentActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaymentActionPerformed

    private void txtpaymentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaymentKeyTyped
        Number(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_txtpaymentKeyTyped

    private void countchangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countchangeMouseClicked

    }//GEN-LAST:event_countchangeMouseClicked

    private void countchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countchangeActionPerformed
        // TODO add your handling code here:
     double Result;
     Frm_Chasier obj = new Frm_Chasier();
        obj.setTotal(Double.parseDouble(total.getText()));
        obj.setLbIDHeader(Integer.parseInt(lbIDHeader.getText()));
        obj.setPayment(Double.parseDouble(txtpayment.getText()));
        obj.setIdtotrans(Integer.parseInt(idtotrans.getText()));
        int i = obj.doChange();
        if(i == 1)
        {
            Result = obj.getResult();  
            change1.setText(Double.toString(Result));
        }
        else{
            System.out.println("Payment Failed!");
        }
        
        int ii = obj.doTransac();
        if(ii == 1)
        {
            JOptionPane.showMessageDialog(null, "Transaction Success! Thank You!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Transaction failed");
        }
    }//GEN-LAST:event_countchangeActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked

        
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
       
        try{
            int QtyTrans1, Stock1, Result1;
            Stock1 = Integer.parseInt(tstock1.getText());
            QtyTrans1 = Integer.parseInt(qty1.getText());
            Result1 = Stock1 + QtyTrans1;
            
        double result2, total1, subtotal;
        total1 = Double.parseDouble(total.getText());
        subtotal = Double.parseDouble(subtot.getText());
        result2 = total1-subtotal;
        total.setText(Double.toString(result2));
            
            stat = con.prepareStatement(UP);
            stat.setString(1, tidpro1.getText());
            stat.setString(2, Integer.toString(Result1));
            stat.executeUpdate();

            JOptionPane.showMessageDialog(null, "Cancel");
        
            tampilkan1();

            try{
            stat = con.prepareStatement("delete DetailTransac where IDDetTrans = ?");
            stat.setString(1, idDT.getText());
            stat.executeUpdate();
            tampilkan2();
            
            tidpro1.setText("");
            ttitle1.setText("");
            tprice1.setText("");
            qty1.setText("");
            subtot.setText("");                                                        
            tstock1.setText("");
            idDT.setText("");
            
            }
            catch(Exception b){
            
            }
//            stat = con.prepareStatement("delete DetailTrans where IDDetPro = ");

        }
        catch(Exception z){
            JOptionPane.showMessageDialog(null, z);
        }
        
    }//GEN-LAST:event_cancelActionPerformed

    private void newTransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newTransMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_newTransMouseClicked

    private void newTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTransActionPerformed
        // TODO add your handling code here:
        TransHeader th = new TransHeader();
        th.show();
        this.hide();
    }//GEN-LAST:event_newTransActionPerformed

    private void qty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty1ActionPerformed

    private void qty1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_qty1KeyPressed

    private void qty1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qty1KeyTyped
        Number(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_qty1KeyTyped
public String InputDT = "INSERT INTO DetailTransac VALUES (?,?,?,?,?)";
public String UP = "EXEC updatepro ?, ?";
public String selectpro = "Select * From DetailProduct";

    private void count1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_count1MouseClicked
        // TODO add your handling code here:
//        Price1 = Integer.parseInt(tprice1.getText());
//        Qty = Integer.parseInt(qty1.getText());
//        GlobalVariable.SubTotal = Price1*Qty;
//        subtotal1.setText(Integer.toString(GlobalVariable.SubTotal));

    }//GEN-LAST:event_count1MouseClicked

    private void count1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count1ActionPerformed
        
        double Price;
        int QtyTrans;
        Price = Double.parseDouble(tprice1.getText());
        QtyTrans = Integer.parseInt(qty1.getText());
        double subtotal;
        subtotal = Price * QtyTrans;
        subtot.setText(Double.toString(subtotal));
        autodetail();
 
    }//GEN-LAST:event_count1ActionPerformed

    private void tidpro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidpro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidpro1ActionPerformed

    private void addproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addproMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_addproMouseClicked

    private void addproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addproActionPerformed
        // TODO add your handling code here:
        try{
                stat = con.prepareStatement(InputDT);
                stat.setString(1, idDT.getText().trim());
                stat.setString(2, lbIDHeader.getText().trim());
                stat.setString(3, tidpro1.getText());
                stat.setString(4, qty1.getText());
                stat.setDouble(5,  Double.parseDouble(subtot.getText()));
                stat.executeUpdate();
                        
                    tampilkan2();
                    
                    PreparedStatement pst = con.prepareStatement("select sum(subtotal) as SUB from DetailTransac where IDTrans = ?");
                    pst.setString(1, lbIDHeader.getText().trim());
                    rs1 = pst.executeQuery();
                    rs1.next();
                    double result = rs1.getDouble("SUB");
                    total.setText(Double.toString(result));
                    UpdateStock();
                    tampilkan1();
                    
                    
                tidpro1.setText("");
                ttitle1.setText("");
                tprice1.setText("");
                tstock1.setText("");
                qty1.setText("");
                subtot.setText("");
                    
                        }
                        catch(Exception s){
                        JOptionPane.showMessageDialog(null, s);
                        }  
    }//GEN-LAST:event_addproActionPerformed

    private void tballproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tballproMouseClicked
        // TODO add your handling code here:
        try{
             int row = tballpro.rowAtPoint(evt.getPoint());
             String IDDetPro = tballpro.getValueAt(row, 0).toString();
             String Title = tballpro.getValueAt(row, 1).toString();
             String Price = tballpro.getValueAt(row, 4).toString();
             String Stock123 = tballpro.getValueAt(row, 5).toString();
             
             tidpro1.setText(String.valueOf(IDDetPro));
             ttitle1.setText(String.valueOf(Title));
             tprice1.setText(String.valueOf(Price));
             tstock1.setText(String.valueOf(Stock123));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tballproMouseClicked

    private void tbDTransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDTransMouseClicked
        // TODO add your handling code here:
        try{
             int row = tbDTrans.rowAtPoint(evt.getPoint());
             String DT = tbDTrans.getValueAt(row, 0).toString();
             String IDDetPro = tbDTrans.getValueAt(row, 2).toString();
             String Qty4 = tbDTrans.getValueAt(row, 3).toString();
             String sub = tbDTrans.getValueAt(row, 4).toString();
            
             qty1.setText(String.valueOf(Qty4));
             idDT.setText(String.valueOf(DT));
             subtot.setText(String.valueOf(sub));
            
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =  DriverManager.getConnection("jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930");
            String sql = "select *  from DetailProduct where IDDetPro = '"+IDDetPro.trim()+"'";
            PreparedStatement psDisplay = con.prepareStatement(sql);
            ResultSet rsDisplay = psDisplay.executeQuery();
            
            if(rsDisplay.next())
            {
                tidpro1.setText(rsDisplay.getString("IDDetPro"));
                ttitle1.setText(rsDisplay.getString("Title"));
                tprice1.setText(rsDisplay.getString("Price"));
                tstock1.setText(rsDisplay.getString("Stock"));
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid Data");
            }
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_tbDTransMouseClicked

    private void idDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idDTActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        idDT.setVisible(false);
        idtotrans.setVisible(true);
        tidpro1.setEditable(false);
        ttitle1.setEditable(false);
        tprice1.setEditable(false);
        tstock1.setEditable(false);
        subtot.setEditable(false);
        total.setEditable(false);
        tballpro.setEditingColumn(0);
        tballpro.setEditingColumn(1);
        tballpro.setEditingColumn(2);
        tballpro.setEditingColumn(3);
        tballpro.setEditingColumn(4);
        tballpro.setEditingColumn(5);
        tballpro.setEditingColumn(6);
        
        tbDTrans.setEditingColumn(0);
        tbDTrans.setEditingColumn(1);
        tbDTrans.setEditingColumn(2);
        tbDTrans.setEditingColumn(3);
        tbDTrans.setEditingColumn(4);
        autoidT();
    }//GEN-LAST:event_formWindowOpened

    private void idtotransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtotransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtotransActionPerformed
//select IDDetPro, Title, Artist, IDGenre, Price, Stock  from DetailProduct
    private void stitleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stitleKeyTyped
        // TODO add your handling code here:
     try {
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =  DriverManager.getConnection("jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930");
            String sql = "select IDDetPro, Title, Artist, IDGenre, Price, Stock  from DetailProduct where title like +'%'+ '"+stitle.getText().trim()+"' +'%'";
            PreparedStatement psDisplay = con.prepareStatement(sql);
            ResultSet rsDisplay = psDisplay.executeQuery(); 
            tballpro.setModel(DbUtils.resultSetToTableModel(rsDisplay));
           
        } catch (SQLException ex) {
            System.out.println(ex);
        
    }
    }//GEN-LAST:event_stitleKeyTyped

    private void stitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stitleActionPerformed

    private void subtotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotActionPerformed

    private void subtotKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subtotKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotKeyPressed

    private void subtotKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_subtotKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotKeyTyped

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void totalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalKeyPressed

    private void totalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_totalKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addpro;
    private javax.swing.JButton btnlogout1;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel change1;
    private javax.swing.JButton count1;
    private javax.swing.JButton countchange;
    public javax.swing.JLabel date1;
    private javax.swing.JTextField idDT;
    public javax.swing.JLabel idemp1;
    private javax.swing.JTextField idtotrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lbIDHeader;
    private javax.swing.JButton newTrans;
    private javax.swing.JTextField qty1;
    private javax.swing.JTextField stitle;
    private javax.swing.JTextField subtot;
    private javax.swing.JTable tbDTrans;
    private javax.swing.JTable tballpro;
    private javax.swing.JTextField tidpro1;
    private javax.swing.JTextField total;
    private javax.swing.JTextField tprice1;
    private javax.swing.JTextField tstock1;
    private javax.swing.JTextField ttitle1;
    private javax.swing.JTextField txtpayment;
    // End of variables declaration//GEN-END:variables
public void tampilkan1() {     
        int row = mdl3.getRowCount();
        for (int i=0;i<row;i++){
            mdl3.removeRow(0);
        }
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =  DriverManager.getConnection("jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930");
             ResultSet rs = con.createStatement().executeQuery("select IDDetPro, Title, Artist, IDGenre, Price, Stock  from DetailProduct");
            while(rs.next()){
            String[] data={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
            mdl3.addRow(data);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(Cashier.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

public void tampilkan2() {     
        
        try {
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =  DriverManager.getConnection("jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930");
            String sql = "select *  from DetailTransac where IDTrans = '"+lbIDHeader.getText().trim()+"'";
            PreparedStatement psDisplay = con.prepareStatement(sql);
            ResultSet rsDisplay = psDisplay.executeQuery();
            tbDTrans.setModel(DbUtils.resultSetToTableModel(rsDisplay));
           
        } catch (SQLException ex) {
            System.out.println(ex);
        
    }
        
    }
public void UpdateStock() {     
        
        try {
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =  DriverManager.getConnection("jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930");
            int Stock, Qty, Result;
            Stock = Integer.parseInt(tstock1.getText());
            Qty = Integer.parseInt(qty1.getText());
            Result = Stock - Qty;
            String sql = "update detailProduct set Stock = '"+Result+"'  where IDDetPro = '"+tidpro1.getText().trim()+"'";
            PreparedStatement psDisplay = con.prepareStatement(sql);
            int rsDisplay = psDisplay.executeUpdate();
            if(rsDisplay>0)
            {
                JOptionPane.showMessageDialog(null, "Success!");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Invalid command");
            }
          
           
        } catch (SQLException ex) {
            System.out.println(ex);
        
    }

}
}
