/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Main.MainMenu1;
import model.Frm_Login;
import Main.Management;
import com.sun.webkit.event.WCFocusEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Azka
 */
public class Login extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    ResultSet rs1;

    Statement stmt;
    PreparedStatement stat;
    public static String user6;
    public static String idemp;


    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setTitle("Login Admin");
    
    String connectionUrl = "jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930";
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }catch(Exception e){
            System.out.println(e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconlog = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelUsernameadmin1 = new javax.swing.JLabel();
        jLabelPassAdmin = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        btnLoginadmin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnExitloginadmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 179, 233));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconlog.setFont(new java.awt.Font("Lucida Calligraphy", 1, 30)); // NOI18N
        iconlog.setForeground(new java.awt.Color(255, 205, 130));
        iconlog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adminssss.png"))); // NOI18N
        iconlog.setText("Login");
        jPanel1.add(iconlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUsernameadmin1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelUsernameadmin1.setText("Username");
        jPanel3.add(jLabelUsernameadmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 70, -1));

        jLabelPassAdmin.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabelPassAdmin.setText("Password");
        jPanel3.add(jLabelPassAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        jPanel3.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 210, -1));

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        txtpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpassKeyPressed(evt);
            }
        });
        jPanel3.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 210, -1));

        btnLoginadmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLoginadmin.setText("Login");
        btnLoginadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginadminMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLoginadminMousePressed(evt);
            }
        });
        btnLoginadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginadminActionPerformed(evt);
            }
        });
        btnLoginadmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginadminKeyPressed(evt);
            }
        });
        jPanel3.add(btnLoginadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 73, 31));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg1.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 220));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 117, 410, 220));

        btnExitloginadmin.setText("x");
        btnExitloginadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitloginadminMouseClicked(evt);
            }
        });
        jPanel1.add(btnExitloginadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 47, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassKeyPressed

    }//GEN-LAST:event_txtpassKeyPressed

    private void btnLoginadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginadminMouseClicked
        Management ma = new Management();
        ma.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginadminMouseClicked
public String id = "select IDDept from Employee where username = ?";
public String oke = "select * from Employee where  username = ? and passwords = ?"; 
    private void btnLoginadminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginadminMousePressed
Frm_Login obj = new Frm_Login();
obj.setUsername(txtuser.getText());
obj.setPassword(txtpass.getText());
int i = obj.doLogin();
if(i == 2){
    user6 = obj.getUsername();
    System.out.println(user6);
    Cashier cs = new Cashier();
    cs.show();
    this.hide();
}else if(i == 1)
{
    user6 = obj.getUsername();
    System.out.println(user6);
    Management adm = new Management();
    adm.show();
    this.hide();
}else
{
 this.show();
//    System.out.println(i);
//    JOptionPane.showMessageDialog(null, "invalid username and password, Login failed!");
    txtuser.setText("");
    txtpass.setText("");
}
    }//GEN-LAST:event_btnLoginadminMousePressed

    private void btnLoginadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginadminActionPerformed

    }//GEN-LAST:event_btnLoginadminActionPerformed

    private void btnLoginadminKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginadminKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnLoginadminKeyPressed

    private void btnExitloginadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitloginadminMouseClicked
        // TODO add your handling code here:
        MainMenu1 mu = new MainMenu1();
        mu.show();
        this.hide();
    }//GEN-LAST:event_btnExitloginadminMouseClicked

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtuser.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExitloginadmin;
    private javax.swing.JButton btnLoginadmin;
    public javax.swing.JLabel iconlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPassAdmin;
    private javax.swing.JLabel jLabelUsernameadmin1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
