/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.PreparedStatement;
import java.sql.Statement;
import java.awt.event.KeyEvent;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Frm_Login;
import model.Frm_ManagementEmp;
import model.Frm_ManagementPro;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Azka
 */
public class Management extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    Statement stmt;
    PreparedStatement stat;
    
    DefaultTableModel mdl1;
    DefaultTableModel mdl;
    DefaultTableModel mdl4;

//method hanya angka//
 private void Number (java.awt.event.KeyEvent evt)
    {
       char c = evt.getKeyChar();
           if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE)))
           {
                evt.consume();
           }
    }

    public Management(){
        initComponents();
        setTitle("Menu Admin");
//tampil tablepro//
        String[] judul={"ID Product","IDType","Title", "Artist", "Pub_Year", "IDGenre", "Price", "Stock"};
        mdl1 = new DefaultTableModel(judul,0);
        tbpro.setModel(mdl1);
        tampil();

        tbpro.setPreferredScrollableViewportSize(new Dimension(300,300));
        tbpro.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

//tampil tableTrans//
        String[] Trans={"Date","IDEmp","IDTrans", "IDDetTrans", "IDDetPro", "Title", "Qty", "Price", "SubTotal"};
        mdl4 = new DefaultTableModel(Trans,0);
        tbtrans.setModel(mdl4);
        tampilTrans();

        tbtrans.setPreferredScrollableViewportSize(new Dimension(300,300));
        tbtrans.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
//Connection database
        String connectionUrl = "jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930";
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }catch(Exception e){
            System.out.println(e);
        }
        
//for view and editable Employee
    Login a = new Login();
        try{
            stat=con.prepareStatement(dept);
            stat.setString(1,a.user6);
            rs = stat.executeQuery();
            if(rs.next()){
                if(rs.getObject("IDDept").equals("STO")){
                //view tbEmp
                    String[] Emplo={"IDEmp","IDDept","Name","Gender", "Phone", "Username"};
                    mdl =new DefaultTableModel(Emplo,0);
                    tbemp.setModel(mdl);
                    tampil1();
                    tbemp.setPreferredScrollableViewportSize(new Dimension(300,300));
                    tbemp.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                //editable Employee
                    idemp.setEditable(false);
                    iddept.setEditable(false);
                    name.setEditable(false);
                    gender.setEditable(false);
                    phone.setEditable(false);
                    username.setEditable(false);
                    pass.setEditable(false);
                }
                else{
                //view tbEmp
                    String[] Admin={"IDEmp","IDDept","Name","Gender", "Phone", "Username", "Password"};
                    mdl =new DefaultTableModel(Admin,0);
                    tbemp.setModel(mdl);
                    tampil1();
                    tbemp.setPreferredScrollableViewportSize(new Dimension(300,300));
                    tbemp.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                //editable Employee
                    idemp.setEditable(true);
                    iddept.setVisible(true);
                    name.setEditable(true);
                    gender.setVisible(true);
                    phone.setEditable(true);
                    username.setEditable(true);
                    pass.setEditable(true);
                }
           }
           }
            catch (Exception e){
                System.out.println(e);
            }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabAdmin = new javax.swing.JTabbedPane();
        jPanel5Pro = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        idprom = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        titlem = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        yearm = new javax.swing.JComboBox<>();
        pricem = new javax.swing.JTextField();
        stockm = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        delpro = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        artistm = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        typeprom = new javax.swing.JComboBox<>();
        btnupm = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbpro = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        genrem = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        titlem1 = new javax.swing.JTextField();
        inputpro1 = new javax.swing.JButton();
        panelEmp = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        idemp = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        pass = new javax.swing.JTextField();
        inputemp = new javax.swing.JButton();
        gender = new javax.swing.JComboBox<>();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbemp = new javax.swing.JTable();
        upemp = new javax.swing.JButton();
        delemp = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        iddept = new javax.swing.JComboBox<>();
        jPanel4Trans = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbtrans = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        datesearch = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 179, 232));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 210, 144));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/adminssss.png"))); // NOI18N
        jLabel1.setText("Management");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 90));

        tabAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("ID_Product");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        idprom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpromActionPerformed(evt);
            }
        });
        jPanel8.add(idprom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 230, -1));

        jLabel12.setText("Artist");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel8.add(titlem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 88, 230, -1));

        jLabel20.setText("Year");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        yearm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Year -", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016" }));
        yearm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearmActionPerformed(evt);
            }
        });
        jPanel8.add(yearm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 90, -1));

        pricem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pricemActionPerformed(evt);
            }
        });
        pricem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pricemKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pricemKeyTyped(evt);
            }
        });
        jPanel8.add(pricem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 230, -1));

        stockm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockmActionPerformed(evt);
            }
        });
        stockm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stockmKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                stockmKeyTyped(evt);
            }
        });
        jPanel8.add(stockm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 230, -1));

        jLabel21.setText("Stock");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel22.setText("Price");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        delpro.setText("Delete");
        delpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delproActionPerformed(evt);
            }
        });
        jPanel8.add(delpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 70, -1));

        jLabel15.setText("Title");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 91, -1, -1));
        jPanel8.add(artistm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 230, -1));

        jLabel24.setText("Genre");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));
        jPanel8.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(911, 57, 586, 175));

        typeprom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Type -", "FLM", "MSC" }));
        typeprom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typepromActionPerformed(evt);
            }
        });
        jPanel8.add(typeprom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 90, -1));

        btnupm.setText("Update");
        btnupm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupmActionPerformed(evt);
            }
        });
        jPanel8.add(btnupm, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 70, -1));

        tbpro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDDetPro", "IDType", "Title", "Artist", "Pub_year", "IDGenre", "Price", "Stock"
            }
        ));
        tbpro.setEnabled(false);
        tbpro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbproMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbpro);

        jPanel8.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 490, 270));

        jLabel23.setText("Type");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        genrem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Genre -", "ACT", "FAN", "ANI", "HOR", "ROM", "COM", "POP", "ROC", "BLU", "RNB", "JAZ", "HIP" }));
        genrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genremActionPerformed(evt);
            }
        });
        jPanel8.add(genrem, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 90, -1));

        jLabel18.setText("Search Title");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 80, 20));

        titlem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titlem1ActionPerformed(evt);
            }
        });
        titlem1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                titlem1KeyTyped(evt);
            }
        });
        jPanel8.add(titlem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 230, 30));

        inputpro1.setText("Save");
        inputpro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputpro1ActionPerformed(evt);
            }
        });
        jPanel8.add(inputpro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        javax.swing.GroupLayout jPanel5ProLayout = new javax.swing.GroupLayout(jPanel5Pro);
        jPanel5Pro.setLayout(jPanel5ProLayout);
        jPanel5ProLayout.setHorizontalGroup(
            jPanel5ProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 865, Short.MAX_VALUE)
        );
        jPanel5ProLayout.setVerticalGroup(
            jPanel5ProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabAdmin.addTab("Product", jPanel5Pro);

        jLabel25.setText("IDEmployee");

        idemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idempActionPerformed(evt);
            }
        });

        jLabel17.setText("Name");

        jLabel13.setText("Gender");

        jLabel26.setText("Phone");

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usernameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                usernameKeyTyped(evt);
            }
        });

        jLabel27.setText("Username");

        jLabel28.setText("Passsword");

        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passKeyTyped(evt);
            }
        });

        inputemp.setText("Save");
        inputemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputempMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputempMousePressed(evt);
            }
        });
        inputemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputempActionPerformed(evt);
            }
        });

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Gender -", "Male", "Female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });

        tbemp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDEmp", "Name", "Gender", "Phone", "Username", "Password"
            }
        ));
        tbemp.setEnabled(false);
        tbemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbempMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tbemp);

        upemp.setText("Update");
        upemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upempActionPerformed(evt);
            }
        });

        delemp.setText("Delete");
        delemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delempActionPerformed(evt);
            }
        });

        jLabel31.setText("IDDept");

        iddept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Department -", "ADM", "STO", "CAS" }));
        iddept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iddeptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEmpLayout = new javax.swing.GroupLayout(panelEmp);
        panelEmp.setLayout(panelEmpLayout);
        panelEmpLayout.setHorizontalGroup(
            panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmpLayout.createSequentialGroup()
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel13)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel17)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(idemp, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iddept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelEmpLayout.createSequentialGroup()
                            .addComponent(inputemp)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(upemp)
                            .addGap(18, 18, 18)
                            .addComponent(delemp, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        panelEmpLayout.setVerticalGroup(
            panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelEmpLayout.createSequentialGroup()
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iddept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEmpLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel28))
                            .addGroup(panelEmpLayout.createSequentialGroup()
                                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(panelEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(inputemp)
                                    .addComponent(delemp)
                                    .addComponent(upemp))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tabAdmin.addTab("Employee", panelEmp);

        jPanel4Trans.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbtrans.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbtrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Date", "ID_Transaction", "ID_Customer", "ID_Product", "Title", "Quantity", "Total Price"
            }
        ));
        jScrollPane9.setViewportView(tbtrans);

        jPanel4Trans.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 670, 250));

        jLabel29.setText("Search Date");
        jPanel4Trans.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, 20));

        datesearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datesearchActionPerformed(evt);
            }
        });
        datesearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datesearchKeyTyped(evt);
            }
        });
        jPanel4Trans.add(datesearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 230, 30));

        tabAdmin.addTab("Transaction", jPanel4Trans);

        jPanel1.add(tabAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 870, 370));
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, -1));

        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogout.setText("Log out");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 40, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg2.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 public void autoidDPro()
    {
        try
        {
            String sql = "select top 1 IDDetPro FROM DetailProduct order by IDDetPro desc";
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery(sql);
            
            if(rs.next())
            {
                String ID = rs.getString("IDDetPro");
                String potong = ID.substring(1);
                int nextid = Integer.parseInt(potong) + 1;
                
                if (nextid<10)
                {
                    ID = "1000" + nextid;
                }
                else if (nextid < 100)
                {
                    ID = "100" + nextid;
                }
                else if (nextid < 1000)
                {
                    ID = "10" + nextid;
                }
                else if (nextid < 10000)
                {
                    ID = "1" + nextid;
                }
                idprom.setText(ID);
                
            }
            else
            {
                idprom.setText("10001");
            }
         }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
 
 public void autoidDEmp()
    {
        try
        {
            String sql = "select top 1 IDEmp FROM Employee order by IDEmp desc";
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery(sql);
            
            if(rs.next())
            {
                String ID = rs.getString("IDEmp");
                String potong = ID.substring(1);
                int nextid = Integer.parseInt(potong) + 1;
                
                if (nextid<10)
                {
                    ID = "300" + nextid;
                }
                else if (nextid < 100)
                {
                    ID = "30" + nextid;
                }
                else if (nextid < 1000)
                {
                    ID = "3" + nextid;
                }
                idemp.setText(ID);
                
            }
            else
            {
                idemp.setText("3001");
            }
         }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        MainMenu1 mu = new MainMenu1();
        mu.show();
        this.hide();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void typepromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typepromActionPerformed
//        // TODO add your handling code here:
      
    }//GEN-LAST:event_typepromActionPerformed

    private void genremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genremActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genremActionPerformed

    private void pricemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pricemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pricemActionPerformed

    private void stockmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockmActionPerformed

    private void pricemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pricemKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_pricemKeyPressed

    private void stockmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockmKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_stockmKeyPressed

    private void pricemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pricemKeyTyped
        // TODO add your handling code here:
          Number(evt);
    }//GEN-LAST:event_pricemKeyTyped

    private void stockmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stockmKeyTyped
        // TODO add your handling code here:
        Number(evt);
    }//GEN-LAST:event_stockmKeyTyped

    private void idpromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpromActionPerformed
public String UP = "EXEC UpdateProduct ?, ?, ?";
    public String select = "Select * From DetailProduct";
    private void btnupmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupmActionPerformed
        // TODO add your handling code here:
Frm_ManagementPro obj = new Frm_ManagementPro();
    obj.setIdpro(idprom.getText());
    obj.setPrice(pricem.getText());
    obj.setStock(stockm.getText());
    int i = obj.doUpdatePro();
        System.out.println(i);
    if(i == 1)
        {
            try{
                stat = con.prepareStatement(select);
                rs = stat.executeQuery();
                mdl1.fireTableDataChanged();
                tbpro.setModel(DbUtils.resultSetToTableModel(rs));;
            //reset
                idprom.setText("");
                typeprom.setSelectedItem("- Type -");
                titlem.setText("");
                artistm.setText("");
                yearm.setSelectedItem("- Year -");
                genrem.setSelectedItem("- Genre -");
                pricem.setText("");
                stockm.setText("");
                
                autoidDPro();
                }
            catch (Exception e){
            System.out.println(e);
            }            
        }else
        {
            idprom.setText("");
            typeprom.setSelectedItem("- Type -");
            titlem.setText("");
            artistm.setText("");
            yearm.setSelectedItem("- Year -");
            genrem.setSelectedItem("- Genre -");
            pricem.setText("");
            stockm.setText("");
        }
    }//GEN-LAST:event_btnupmActionPerformed

    private void idempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idempActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_idempActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneKeyPressed

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
        // TODO add your handling code here:
        Number(evt);
    }//GEN-LAST:event_phoneKeyTyped

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyPressed

    private void usernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameKeyTyped

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_passKeyPressed

    private void passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_passKeyTyped
public String select1 = "Select * From Employee";
public String dept = "Select IDDept from employee where username = ?";
    private void inputempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputempActionPerformed
        // TODO add your handling code here:
 Frm_ManagementEmp obj = new Frm_ManagementEmp();
    obj.setIdadm(idemp.getText());
    obj.setAiddept((String) iddept.getSelectedItem());
    obj.setAname(name.getText()); 
    obj.setAgdr((String) gender.getSelectedItem());
    obj.setAphone(phone.getText());
    obj.setAuser(username.getText());
    obj.setApass(pass.getText());
    obj.setIdname(txtname.getText());
    int i = obj.doInsertEmp();
    
        if(i == 1)
        {
            try{
            tampil1();
            stat = con.prepareStatement(select1);
            rs = stat.executeQuery();
            tbemp.setModel(DbUtils.resultSetToTableModel(rs));
        //reset
            idemp.setText("");
            iddept.setSelectedItem("- Department -");
            name.setText("");
            gender.setSelectedItem("- Gender -");
            phone.setText("");
            username.setText("");
            pass.setText("");
            idemp.requestFocus();
            autoidDEmp();
            }
            catch (Exception e){
            System.out.println(e);
            }            
        }else
        {
            idemp.setText("");
            iddept.setSelectedItem("- Department -");
            name.setText("");
            gender.setSelectedItem("- Gender -");
            phone.setText("");
            username.setText("");
            pass.setText("");
            idemp.requestFocus();
        }   
    }//GEN-LAST:event_inputempActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void inputempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputempMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_inputempMouseClicked
public String UP2 = "EXEC updateEmp ?,?,?,?,?";
//    public String Username = "Select Username from Employee where username = ?";
    private void upempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upempActionPerformed
    // TODO add your handling code here:
Frm_ManagementEmp obj = new Frm_ManagementEmp();
    obj.setIdadm(idemp.getText());
    obj.setAiddept((String) iddept.getSelectedItem());
    obj.setAphone(phone.getText());
    obj.setAuser(username.getText());
    obj.setApass(pass.getText());
    obj.setIdname(txtname.getText());
    int i = obj.doUpdateEmp();

    if(i == 1)
        {
            try{
                stat = con.prepareStatement(select1);
                rs = stat.executeQuery();
                mdl.fireTableDataChanged();
                tbemp.setModel(DbUtils.resultSetToTableModel(rs));
            //reset
                idemp.setText("");
                iddept.setSelectedItem("- Department -");
                name.setText("");
                gender.setSelectedItem("- Gender -");
                phone.setText("");
                username.setText("");
                pass.setText("");
                idemp.requestFocus();
                
                autoidDEmp();
                }
            catch (Exception e){
            System.out.println(e);
            }            
        }else
        {
            idemp.setText("");
            iddept.setSelectedItem("- Department -");
            name.setText("");
            gender.setSelectedItem("- Gender -");
            phone.setText("");
            username.setText("");
            pass.setText("");
            idemp.requestFocus();
        }
    }//GEN-LAST:event_upempActionPerformed

    private void delproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delproActionPerformed
        // TODO add your handling code here:
Frm_ManagementPro obj = new Frm_ManagementPro();
    obj.setIdpro(idprom.getText());
    obj.setIdname(txtname.getText());
    int i = obj.doDeletePro();

    if(i == 1)
        {
            try{
                stat = con.prepareStatement(select);
                rs = stat.executeQuery();
                mdl1.fireTableDataChanged();
                tbpro.setModel(DbUtils.resultSetToTableModel(rs));;
            //reset
                idprom.setText("");
                typeprom.setSelectedItem("- Type -");
                titlem.setText("");
                artistm.setText("");
                yearm.setSelectedItem("- Year -");
                genrem.setSelectedItem("- Genre -");
                pricem.setText("");
                stockm.setText("");
                autoidDPro();
                }
            catch (Exception e){
            System.out.println(e);
            }            
        }else
        {
            JOptionPane.showMessageDialog(rootPane, "Insert failed!");
            idprom.setText("");
                typeprom.setSelectedItem("- Type -");
                titlem.setText("");
                artistm.setText("");
                yearm.setSelectedItem("- Year -");
                genrem.setSelectedItem("- Genre -");
                pricem.setText("");
                stockm.setText("");
        }
    }//GEN-LAST:event_delproActionPerformed

    private void delempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delempActionPerformed
        // TODO add your handling code here:
        Login a = new Login();
        try
   {
        stat=con.prepareStatement(dept);
        stat.setString(1,a.user6);
        rs = stat.executeQuery();
        if(rs.next())
           {
            if(rs.getObject("IDDept").equals("STO"))
            {
            JOptionPane.showMessageDialog(null, "DENIED ACCESS!");
            idemp.setText("");
            iddept.setSelectedItem("- Department -");
            name.setText("");
            gender.setSelectedItem("- Gender -");
            phone.setText("");
            username.setText("");
            pass.setText("");
            
            }
            else
            {
                try{
                   stat = con.prepareStatement("delete Employee where IDEmp = ?");
                    stat.setString(1, idemp.getText());
                    stat.executeUpdate();
                    stat = con.prepareStatement(select1);
                   rs = stat.executeQuery();
                    

                   JOptionPane.showMessageDialog(rootPane, "Delete success!");
                   mdl.fireTableDataChanged();
                   tbemp.setModel(DbUtils.resultSetToTableModel(rs));
                   
        idemp.setText("");
        iddept.setSelectedItem("- Department -");
        name.setText("");
        gender.setSelectedItem("- Gender -");
        phone.setText("");
        username.setText("");
        pass.setText("");
        
                   
                   }catch(Exception w)
                    {
                    String msg = w.getMessage();
                    if(w.getMessage().equals(msg)){
                        
                    }}
            }
           }
   }
   catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
//                
    }//GEN-LAST:event_delempActionPerformed

    private void iddeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iddeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iddeptActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void tbproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbproMouseClicked
        // TODO add your handling code here:
        try{
             int row = tbpro.rowAtPoint(evt.getPoint());
             String IDDetPro = tbpro.getValueAt(row, 0).toString();
             String Type = tbpro.getValueAt(row, 1).toString();
             String Title = tbpro.getValueAt(row, 2).toString();
             String Artist = tbpro.getValueAt(row, 3).toString();
             String Year = tbpro.getValueAt(row, 4).toString();
             String Genre = tbpro.getValueAt(row, 5).toString();
             String Price = tbpro.getValueAt(row, 6).toString();
             String Stock = tbpro.getValueAt(row, 7).toString();
             
             idprom.setText(String.valueOf(IDDetPro));
             typeprom.setSelectedItem(String.valueOf(Type));
             titlem.setText(String.valueOf(Title));
             artistm.setText(String.valueOf(Artist));
             yearm.setSelectedItem(String.valueOf(Year));
             genrem.setSelectedItem(String.valueOf(Genre));
             pricem.setText(String.valueOf(Price));
             stockm.setText(String.valueOf(Stock));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_tbproMouseClicked

    private void tbempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbempMouseClicked
        // TODO add your handling code here:
        try{
             int row = tbemp.rowAtPoint(evt.getPoint());
             String IDEmp = tbemp.getValueAt(row, 0).toString();
             String Dept = tbemp.getValueAt(row, 1).toString();
             String Name = tbemp.getValueAt(row, 2).toString();
             String Gender = tbemp.getValueAt(row, 3).toString();
             String Phone = tbemp.getValueAt(row, 4).toString();
             String User = tbemp.getValueAt(row, 5).toString();
             String Pass = tbemp.getValueAt(row, 6).toString();
             
             idemp.setText(String.valueOf(IDEmp));
             iddept.setSelectedItem(String.valueOf(Dept));
             name.setText(String.valueOf(Name));
             gender.setSelectedItem(String.valueOf(Gender));
             phone.setText(String.valueOf(Phone));
             username.setText(String.valueOf(User));
             pass.setText(String.valueOf(Pass));
             
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_tbempMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //set nama admin yang login
        Login log = new Login();
        txtname.setText(log.user6);
        txtname.setEditable(false);
        
        autoidDPro();
        idprom.setEditable(false);
        autoidDEmp();
        idemp.setEditable(false);
    }//GEN-LAST:event_formWindowOpened

    private void inputpro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputpro1ActionPerformed
Frm_ManagementPro obj = new Frm_ManagementPro();
    obj.setIdpro(idprom.getText());
    obj.setType((String) typeprom.getSelectedItem());
    obj.setTitle(titlem.getText());
    obj.setArtist(artistm.getText());
    obj.setYear((String) yearm.getSelectedItem());
    obj.setGenre((String) genrem.getSelectedItem());
    obj.setPrice(pricem.getText());
    obj.setStock(stockm.getText());
    obj.setIdname(txtname.getText());
    int i = obj.doInsertPro();
        
        if(i == 1)
        {
            try{
            tampil();
            stat = con.prepareStatement(select);
            rs = stat.executeQuery();
            tbpro.setModel(DbUtils.resultSetToTableModel(rs));
        //reset
            typeprom.setSelectedItem("- Type -");
            titlem.setText("");
            artistm.setText("");
            yearm.setSelectedItem("- Year -");
            genrem.setSelectedItem("- Genre -");
            pricem.setText("");
            stockm.setText("");
            autoidDPro();
            }
            catch (Exception e){
            System.out.println(e);
            }            
        }else
        {
            
            typeprom.setSelectedItem("- Type -");
            titlem.setText("");
            artistm.setText("");
            yearm.setSelectedItem("- Year -");
            genrem.setSelectedItem("- Genre -");
            pricem.setText("");
            stockm.setText("");
            autoidDPro();
        }      
    }//GEN-LAST:event_inputpro1ActionPerformed

    private void titlem1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titlem1KeyTyped
try {
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =  DriverManager.getConnection("jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930");
            String sql = "select *  from DetailProduct where Title like +'%'+ '"+titlem1.getText().trim()+"' +'%'";
            PreparedStatement psDisplay = con.prepareStatement(sql);
            ResultSet rsDisplay = psDisplay.executeQuery();
            tbpro.setModel(DbUtils.resultSetToTableModel(rsDisplay));
           
        } catch (SQLException ex) {
            System.out.println(ex);
        
    }        // TODO add your handling code here:
    }//GEN-LAST:event_titlem1KeyTyped

    private void datesearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datesearchKeyTyped
        // TODO add your handling code here:
       try {
            //Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =  DriverManager.getConnection("jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930");
            String sql = "select TR.DateTrans, TR.IDEmp, TR.IDTrans, D.IDDetTrans, D.IDDetPro,DP.Title, D.Qty, DP.Price, D.SubTotal from DetailTransac D INNER JOIN Transac TR  ON TR.IDTrans = D.IDTrans INNER JOIN TotalTrans T ON T.IDTrans = TR.IDTrans INNER JOIN DetailProduct DP ON DP.IDDetPro = D.IDDetPro where DateTrans like +'%'+ '"+datesearch.getText().trim()+"' +'%'";
            PreparedStatement psDisplay = con.prepareStatement(sql);
            ResultSet rsDisplay = psDisplay.executeQuery();
            tbtrans.setModel(DbUtils.resultSetToTableModel(rsDisplay));
           
        } catch (SQLException ex) {
            System.out.println(ex);
        
    }
    }//GEN-LAST:event_datesearchKeyTyped

    private void datesearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datesearchActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_datesearchActionPerformed

    private void titlem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titlem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titlem1ActionPerformed

    private void inputempMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputempMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputempMousePressed

    private void yearmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Management().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Management.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField artistm;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnupm;
    private javax.swing.JTextField datesearch;
    private javax.swing.JButton delemp;
    private javax.swing.JButton delpro;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JComboBox<String> genrem;
    private javax.swing.JComboBox<String> iddept;
    private javax.swing.JTextField idemp;
    private javax.swing.JTextField idprom;
    private javax.swing.JButton inputemp;
    private javax.swing.JButton inputpro1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4Trans;
    private javax.swing.JPanel jPanel5Pro;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField name;
    private javax.swing.JPanel panelEmp;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField pricem;
    private javax.swing.JTextField stockm;
    private javax.swing.JTabbedPane tabAdmin;
    public javax.swing.JTable tbemp;
    private javax.swing.JTable tbpro;
    private javax.swing.JTable tbtrans;
    private javax.swing.JTextField titlem;
    private javax.swing.JTextField titlem1;
    private javax.swing.JTextField txtname;
    private javax.swing.JComboBox<String> typeprom;
    private javax.swing.JButton upemp;
    private javax.swing.JTextField username;
    private javax.swing.JComboBox<String> yearm;
    // End of variables declaration//GEN-END:variables

   

 public void tampil() {     
        int row = mdl1.getRowCount();
        
        for (int i=0;i<row;i++){
            mdl1.removeRow(0);
        }
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =  DriverManager.getConnection("jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930");
            ResultSet rs = con.createStatement().executeQuery("select * from DetailProduct");
            while(rs.next()){
            String[] data={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8)};
            mdl1.addRow(data);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(Management.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
 
 public void tampil1() {
        int row = mdl.getRowCount();
        for (int i=0;i<row;i++){
            mdl.removeRow(0);
        }
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =  DriverManager.getConnection("jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930");
            ResultSet rs = con.createStatement().executeQuery("select * from Employee");
            while(rs.next()){
            String[] emp={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7)};
            mdl.addRow(emp);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(Management.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
 
 public void tampilTrans() {     
        int row = mdl4.getRowCount();
        
        for (int i=0;i<row;i++){
            mdl4.removeRow(0);
        }
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con =  DriverManager.getConnection("jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930");
            ResultSet rs = con.createStatement().executeQuery("select	TR.DateTrans, TR.IDEmp, TR.IDTrans, D.IDDetTrans, D.IDDetPro,DP.Title, D.Qty, DP.Price, D.SubTotal from DetailTransac D INNER JOIN Transac TR  ON TR.IDTrans = D.IDTrans INNER JOIN TotalTrans T ON T.IDTrans = TR.IDTrans INNER JOIN DetailProduct DP ON DP.IDDetPro = D.IDDetPro");
            while(rs.next()){
            String[] data={rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)};
            mdl4.addRow(data);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
        Logger.getLogger(Management.class.getName()).log(Level.SEVERE, null, ex);
    }
  }
}