/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Azka
 */
public class TransHeader extends javax.swing.JFrame {
    Connection con;
    ResultSet rs2;
    ResultSet rs1;
    Statement stmt;
    PreparedStatement stat;
    String idH;
    /**
     * Creates new form TransHeader
     */
    public TransHeader() {
        initComponents();
        txtIDEmp.setText(Login.user6);
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");
        txtDate.setText(s.format(d));
         String connectionUrl = "jdbc:sqlserver://DESKTOP-764PK2R;databaseName=Project_DVD;user=sa;password=azkady1930";
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(connectionUrl);
            stmt = con.createStatement();
        }catch(Exception e){
            System.out.println(e);
        }
//ambilIDEmp
    
    Login a = new Login();
    try
                {
                    stat=con.prepareStatement("Select IDEmp from employee where username = ?");
                    stat.setString(1, a.user6);
                    rs1 = stat.executeQuery();
                    if(rs1.next())
                    {
                        txtIDEmp.setText((String) rs1.getString("IDEmp"));
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Error");
                    }
                    }
                catch(Exception w)
                    {
                      JOptionPane.showMessageDialog(null, w.toString());
                    }
    }
//public String idemp = ;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        iconlog = new javax.swing.JLabel();
        saveth = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtIDEmp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel2.setText("Date");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel3.setText("ID Emp");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 154, -1, 30));

        iconlog.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        iconlog.setForeground(new java.awt.Color(255, 205, 130));
        iconlog.setText("TransHeader");
        jPanel1.add(iconlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 60));

        saveth.setText("Save");
        saveth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savethActionPerformed(evt);
            }
        });
        saveth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                savethKeyPressed(evt);
            }
        });
        jPanel1.add(saveth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 136, -1));

        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 136, -1));
        jPanel1.add(txtIDEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 136, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/as.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg2.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void autoidDT()
    {
        try
        {
            String sql = "select top 1 IDTrans FROM Transac order by IDTrans desc";
            Statement state = con.createStatement();
            ResultSet rs = state.executeQuery(sql);
            
            if(rs.next())
            {
                String ID = rs.getString("IDTrans");
                String potong = ID.substring(1);
                int nextid = Integer.parseInt(potong) + 1;
                
                if (nextid<10)
                {
                    ID = "2000" + nextid;
                }
                else if (nextid < 100)
                {
                    ID = "200" + nextid;
                }
                else if (nextid < 1000)
                {
                    ID = "20" + nextid;
                }
                else if (nextid < 10000)
                {
                    ID = "2" + nextid;
                }
                txtID.setText(ID);
                
            }
            else
            {
                txtID.setText("20001");
            }
         }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       autoidDT();
       txtID.setEditable(false);
       txtDate.setEditable(false);
       txtIDEmp.setEditable(false);
    }//GEN-LAST:event_formWindowOpened

    private void savethKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_savethKeyPressed
        
    }//GEN-LAST:event_savethKeyPressed
//public static String IDHeader;
public String insertT = "INSERT INTO Transac VALUES(?,?,getdate())";

    private void savethActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savethActionPerformed
        // TODO add your handling code here:
 try{
             stat = con.prepareStatement(insertT);
             String idth = txtID.getText();
             String idemp = txtIDEmp.getText();
             stat.setString(1, idth);
             stat.setString(2, idemp);
             stat.executeUpdate();
                        
//             JOptionPane.showMessageDialog(rootPane, "Input Trans Header Success!");
             Cashier ch = new Cashier();
             idH = txtID.getText();
             ch.lbIDHeader.setText(idH);
             ch.date1.setText(txtDate.getText());
             ch.idemp1.setText(txtIDEmp.getText());
             ch.show();
             this.hide();   
                }catch(Exception w)
                {
                    //String msg = w.getMessage();
                    //if(w.getMessage().equals(msg)){
                        JOptionPane.showMessageDialog(null, w.toString());
                    //}
                    }
    }//GEN-LAST:event_savethActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransHeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransHeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransHeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransHeader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransHeader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel iconlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton saveth;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDEmp;
    // End of variables declaration//GEN-END:variables
}
